/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElImg: (typeof import('element-plus/es'))['ElImg']
  const ElNotification: (typeof import('element-plus/es'))['ElNotification']
  const ElPagination: (typeof import('element-plus/es'))['ElPagination']
}
